name: CI

on:
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:

  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        runner: [ ubuntu, windows ]
    runs-on: ${{ matrix.runner }}-latest
    steps:
      - name: check out
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Gradle build action
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false
          gradle-home-cache-cleanup: true

      - name: unit tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          cache-read-only: false
          gradle-home-cache-cleanup: true

  all-checks:
    if: always()
    runs-on: ubuntu-latest
    needs:
      - unit-tests
    steps:
      - name: require that all other jobs have passed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
