name: Renovate

on:
  schedule:
    - cron: "0 12 * * *" # noon daily
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup node
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1
        id: app-token
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}

      - name: Renovate
        uses: renovatebot/github-action@e1db501385ddcccbaae6fb9c06befae04f379f23 # v40.2.10
        with:
          configurationFile: .github/renovate-sh.json
          token: ${{ steps.app-token.outputs.token }}
#        env:
#          LOG_LEVEL: debug
